array_width                             =   0
attr_fn_like_width                      =   0
binop_separator                         =   "Front"
blank_lines_lower_bound                 =   0
blank_lines_upper_bound                 =   1
brace_style                             =   "AlwaysNextLine"
chain_width                             =   0
combine_control_expr                    =   false
comment_width                           =   80
condense_wildcard_suffixes              =   true
control_brace_style                     =   "AlwaysNextLine"
edition                                 =   "2018"
empty_item_single_line                  =   true
enum_discrim_align_threshold            =   40
error_on_line_overflow                  =   false
error_on_unformatted                    =   true
fn_params_layout                        =   "Vertical"
fn_call_width                           =   0
fn_single_line                          =   true
force_explicit_abi                      =   true
force_multiline_blocks                  =   false
format_code_in_doc_comments             =   true
format_macro_matchers                   =   true
format_macro_bodies                     =   true
format_strings                          =   true
hard_tabs                               =   false
hide_parse_errors                       =   false
imports_indent                          =   "Block"
imports_layout                          =   "Vertical"
indent_style                            =   "Block"
inline_attribute_width                  =   0
license_template_path                   =   ""
match_arm_blocks                        =   true
match_arm_leading_pipes                 =   "Never"
match_block_trailing_comma              =   true
max_width                               =   80
merge_derives                           =   true
merge_imports                           =   true
newline_style                           =   "Unix"
normalize_comments                      =   false
normalize_doc_attributes                =   true
overflow_delimited_expr                 =   false
remove_nested_parens                    =   true
reorder_impl_items                      =   true
reorder_imports                         =   true
reorder_modules                         =   true
required_version                        =   CARGO_PKG_VERSION
single_line_if_else_max_width           =   0
space_after_colon                       =   true
space_before_colon                      =   false
spaces_around_ranges                    =   true
space_around_attr_eq                    =   true
struct_field_align_threshold            =   40
struct_lit_single_line                  =   false
struct_lit_width                        =   0
struct_variant_width                    =   0
tab_spaces                              =   2
trailing_comma                          =   "Always"
trailing_semicolon                      =   true
type_punctuation_density                =   "Wide"
unstable_features                       =   true
use_field_init_shorthand                =   true
width_heuristics                        =   "Off"
use_try_shorthand                       =   true
version                                 =   "Two"
where_single_line                       =   true
wrap_comments                           =   true
zzz_do_fail                             =   "do not use rustfmt yet!"
